### ISSUE TITLE
Example of `related_work.jsonl` file

### ISSUE THREAD

**Issue by Martin36** [jacklxc/CORWA#1]
I am trying to run your model on my own dataset and was wondering if it would be possible for you to share your `related_work.jsonl` file, to use as a reference for the data structure.

Thanks!

**Comment by jacklxc** [comment]
As you can see from [pipeline/S2ORC_parse_related_work.ipynb](https://github.com/jacklxc/CORWA/blob/main/pipeline/S2ORC_parse_related_work.ipynb), `related_work.jsonl` is derived from `metadata` and `pdf_parses` from S2ORC dataset. You can go to [S2ORC GitHub](https://github.com/allenai/s2orc#valid-release-versions) to get an idea of what they look like. Basically, the "related_work" attribute contains a subset of "body_text" paragraphs in S2ORC pdf_parses whose section title contains the string "related".

**Comment by Martin36** [comment]
Thanks for the response. I wanted to skip the whole step of using S2ORC and write a converter for my own dataset. In that case it would be nice to have a reference to what the input data should look like. However, I managed to extract that information from the file that you linked to.
