### ISSUE TITLE
Confusion regarding citation span detection

### ISSUE THREAD

**Issue by jessicalamjh** [jacklxc/CORWA#3]
Hello, first of all thanks for the nice dataset. One part of your paper that caught my attention is Section 3.1.2 Citation Span Detection, where you defined a citation span as "the span of text whose information is directly derived from a specific cited paper". To my understanding, the annotation protocol relevant to this section is like so:

- If the cited paper is explained, then the annotators were to label the explanation within the citing paper. The explanation may be only part of a sentence or go across sentence boundaries.
- If the cited paper is not explained, then the annotators were to label the citation mark for the cited paper.

Here's an example of what I think counts as the first case:

- **data/annotated_train/10011032.txt, Line 37**: [BOS] Zhang and Clark (2008) proposed an incremental joint segmentation and POS tagging model, with an effective feature set for Chinese.
- **data/annotated_train/10011032.ann, Line 54**: T56	Dominant 4577 4599	Zhang and Clark (2008)

I expected the annotation to be "incremental joint segmentation and POS tagging model, with an effective feature set for Chinese" instead. Did I maybe understand the explanation of the annotation protocol wrongly? Looking forward to your response.

**Comment by jacklxc** [comment]
Thanks for pointing out. Our training set is machine-labeled first and then corrected by only one annotator. Therefore, with a small possibility there is some annotation error like the one you pointed out. But overall we still claim that the dataset is high quality.
